import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { prisma } from "@/db/prisma";
import { getAppContext } from "@/services/app/get-app-context";
import { buildSignInRedirectPath } from "@/services/auth/redirects";
import { isAiIntegrityExperienceEnabled } from "@/services/ai-integrity/experience";
import { AI_INTEGRITY_RULE_VERSION } from "@/domain/ai-integrity/reconciliation";

export default async function AiIntegrityDashboard() {
  if (!isAiIntegrityExperienceEnabled()) notFound();
  const context = await getAppContext();
  if (!context) redirect(buildSignInRedirectPath("/app/ai-integrity/dashboard"));
  const [grants, batches, mappings, reports] = await Promise.all([
    prisma.aiIntegrityScanGrant.count({ where: { workspaceId: context.workspace.id, status: "ACTIVE", consumedAt: null, order: { status: "PAID" } } }),
    prisma.aiIntegrityImportBatch.findMany({ where: { workspaceId: context.workspace.id }, orderBy: { createdAt: "desc" }, take: 100, select: { id: true, sourceKind: true, fileName: true, duplicateCount: true, createdAt: true } }),
    prisma.aiIntegrityMapping.count({ where: { workspaceId: context.workspace.id, kind: "PROVIDER_PROJECT", status: "CONFIRMED" } }),
    prisma.aiIntegritySnapshot.findMany({ where: { workspaceId: context.workspace.id, ruleVersion: AI_INTEGRITY_RULE_VERSION }, orderBy: { createdAt: "desc" }, take: 20, select: { id: true, windowStart: true, windowEnd: true, createdAt: true, _count: { select: { findings: true } } } }),
  ]);
  const sources = ["STRIPE_REVENUE", "INTERNAL_LEDGER", "PROVIDER_REPORT"];
  const sourceCount = sources.filter((source) => batches.some((b) => b.sourceKind === source && !b.duplicateCount)).length;
  const href = !grants ? "/start" : sourceCount < 3 ? "/app/ai-integrity/imports" : !mappings ? "/app/ai-integrity/attribution" : "/app/ai-integrity/scans";
  return <div className="space-y-6"><section className="rev-shell-hero rev-accent-mist rounded-[30px] p-6 md:p-8"><p className="rev-kicker">Your Integrity workspace</p><h1 className="rev-display-hero mt-4">{reports.length ? "Every read has a paper trail." : "Prepare your first evidence-led read."}</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-[color:var(--text-muted)]">Choose a closed period, prepare all three exports and review the identities. Your report will show what can be compared and where the evidence needs work.</p><Link className="rev-button-primary mt-6" href={href}>{!grants ? "Review the test purchase" : sourceCount < 3 ? "Import your sources" : !mappings ? "Review customer identity" : "Review & run your scan"} →</Link></section>
    <div className="grid gap-3 sm:grid-cols-3">{[["Scans available", String(grants), "Confirmed one-time test purchases"], ["Source types imported", `${sourceCount} / 3`, "Original imports with complete membership"], ["Reports delivered", String(reports.length), "Recent immutable snapshots"]].map(([label, value, copy]) => <div key={label} className="rev-shell-panel rounded-[24px] p-5"><p className="text-xs text-[color:var(--text-muted)]">{label}</p><p className="mt-3 text-2xl font-semibold">{value}</p><p className="mt-3 text-[11px] leading-5 text-[color:var(--text-subtle)]">{copy}</p></div>)}</div>
    <section className="rev-shell-panel rounded-[26px] p-6"><h2 className="text-lg font-semibold">Three sources for the same period</h2><div className="mt-5 grid gap-4 md:grid-cols-3">{sources.map((source, index) => { const batch = batches.find((b) => b.sourceKind === source && !b.duplicateCount); return <div key={source} className="rounded-2xl border border-[color:var(--border)] p-4"><p className="text-xs text-[color:var(--accent)]">0{index + 1}</p><h3 className="mt-3 text-sm font-semibold">{["Stripe revenue", "Internal ledger", "Provider report"][index]}</h3><p className="mt-3 break-all text-xs leading-6 text-[color:var(--text-muted)]">{batch ? batch.fileName : "No complete import yet"}</p><p className="mt-2 text-[10px] text-[color:var(--text-subtle)]">{batch ? "Stored · period and closure reviewed at execution" : "CSV or XLSX · preview before import"}</p></div>; })}</div><p className="mt-4 text-xs leading-6 text-[color:var(--text-subtle)]">Imports alone do not establish comparability. Review project exclusivity, matching units and source closure before execution.</p></section>
    <section className="rev-shell-panel rounded-[26px] p-6"><h2 className="text-lg font-semibold">Your report history</h2><div className="mt-5 space-y-3">{reports.length ? reports.map((report) => <Link key={report.id} href={`/app/ai-integrity/reports/${report.id}`} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-[color:var(--border)] p-4 text-xs"><div><p className="font-semibold">{report.windowStart.toISOString().slice(0, 10)} → {report.windowEnd.toISOString().slice(0, 10)}</p><p className="mt-2 text-[color:var(--text-subtle)]">Created {report.createdAt.toISOString().slice(0, 10)} · synthetic test evidence</p></div><span className="text-[color:var(--accent)]">{report._count.findings} review items · Open report →</span></Link>) : <div className="rounded-2xl border border-dashed border-[color:var(--border)] p-7"><p className="text-sm font-semibold">Your first report will live here.</p><p className="mt-3 text-xs leading-6 text-[color:var(--text-muted)]">Explore the sample to see the coverage, review queue and evidence detail you will receive.</p><Link href="/demo" className="mt-4 inline-block text-xs text-[color:var(--accent)]">Open synthetic demo →</Link></div>}</div></section>
  </div>;
}
