import Link from "next/link";
import { RevoryLogo } from "@/components/brand/RevoryLogo";
import { aiIntegrityDemoResult } from "@/domain/ai-integrity/demo";
import { aiMoney } from "./report-copy";

export function AiMarketingNav() {
  return <header className="mx-auto flex max-w-[1240px] flex-wrap items-center justify-between gap-4 border-b border-[color:var(--border)] px-5 py-5 md:px-8"><Link href="/" aria-label="REVORY home"><RevoryLogo compact /></Link><nav className="flex items-center gap-5 text-xs font-semibold text-[color:var(--text-muted)]"><Link className="hover:text-[color:var(--accent)]" href="/demo">Explore demo</Link><Link className="rev-button-secondary text-xs" href="/start">Start a scan ↗</Link></nav></header>;
}
export function AiMarketingFooter() { return <footer className="mx-auto flex max-w-[1240px] flex-wrap items-center justify-between gap-4 border-t border-[color:var(--border)] px-5 py-8 text-xs text-[color:var(--text-subtle)] md:px-8"><p>REVORY · Revenue & AI Margin Integrity</p><div className="flex gap-5"><Link href="/ai-integrity-preview-policy#security">Security</Link><Link href="/ai-integrity-preview-policy#privacy">Privacy</Link><Link href="/ai-integrity-preview-policy#offer">Test offer</Link></div><p className="w-full text-[10px]">Development preview · Synthetic data · Test checkout · Customer beta requires its release gates.</p></footer>; }

export function AiIntegrityLanding() {
  const result = aiIntegrityDemoResult(), group = result.coverage.groups[0];
  return <main className="ai-integrity-experience min-h-screen overflow-x-clip bg-[color:var(--background)] [font-family:var(--font-dm-sans)]">
    <AiMarketingNav />
    <section className="mx-auto grid max-w-[1240px] items-center gap-12 px-5 pb-20 pt-14 md:px-8 md:pt-20 lg:grid-cols-[1.05fr_1fr] lg:gap-14 lg:pb-28">
      <div><p className="rev-kicker">Revenue & AI Margin Integrity · Preview</p><h1 className="mt-6 [font-family:var(--font-instrument-serif)] text-[clamp(3.3rem,5.5vw,5rem)] font-normal leading-[0.99] tracking-[-0.025em]">Understand your AI spend.<br /><span className="text-[color:var(--accent)]">Follow the evidence.</span></h1><p className="mt-7 max-w-lg text-base leading-8 text-[color:var(--text-muted)]">Bring your Stripe export, internal usage ledger and provider report. See which spend has a customer link, where usage differs, and what needs a closer look.</p><div className="mt-8 flex flex-wrap gap-3"><Link className="rev-button-primary" href="/start">Prepare an Integrity Scan ↗</Link><Link className="rev-button-secondary" href="/demo">See a sample report</Link></div><p className="mt-5 text-xs leading-6 text-[color:var(--text-subtle)]">CSV/XLSX first · Read-only evidence · No call required<br />Development preview; sample data and test purchases only.</p></div>
      <div className="rev-shell-hero rev-accent-mist rounded-[32px] p-5 md:p-7"><div className="flex items-center justify-between gap-2"><p className="text-xs font-semibold">Aster AI · August read</p><span className="rounded-full border border-[color:var(--border-accent)] px-3 py-1 text-[10px] text-[color:var(--accent)]">Synthetic example</span></div><div className="mt-7 grid grid-cols-3 gap-2">{[["Stripe", "Billing context"], ["Internal ledger", "8.64M tokens"], ["Provider", "USD 2,455.75"]].map(([label, text]) => <div key={label} className="min-w-0 rounded-xl border border-[color:var(--border)] p-3"><p className="text-[10px] text-[color:var(--text-subtle)]">{label}</p><p className="mt-2 text-[11px] font-semibold leading-5">{text}</p></div>)}</div><div className="mt-6 rounded-[22px] border border-[color:var(--border-accent)] bg-[color:var(--background-card)] p-5"><div className="flex items-center justify-between gap-3"><p className="text-xs text-[color:var(--text-muted)]">Attribution coverage</p><p className="text-xl font-semibold">{(group.coverageBps! / 100).toFixed(2)}%</p></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-[color:var(--brand-surface)]"><div className="h-full rounded-full bg-[color:var(--accent)]" style={{ width: `${group.coverageBps! / 100}%` }} /></div><p className="mt-3 text-[10px] leading-5 text-[color:var(--text-subtle)]">{aiMoney(group.attributedCost, "USD")} linked to a confirmed exclusive project.</p></div><div className="mt-3 space-y-3">{[["Spend without a customer link", "USD 615.25", "Observed · coverage gap"], ["Usage that doesn't reconcile", "+380,000 tokens", "Calculated · review metering"]].map(([label, amount, basis]) => <div key={label} className="flex flex-wrap justify-between gap-3 rounded-xl border border-[color:var(--border)] px-4 py-4"><div><p className="text-xs font-semibold">{label}</p><p className="mt-1.5 text-[10px] text-[color:var(--text-subtle)]">{basis}</p></div><p className="text-xs font-semibold text-[color:var(--accent)]">{amount}</p></div>)}</div><Link href="/demo" className="mt-5 block text-xs font-semibold text-[color:var(--accent)]">Open the evidence behind this read →</Link></div>
    </section>
    <section className="border-y border-[color:var(--border)] bg-[color:var(--background-secondary)] px-5 py-16 md:px-8"><div className="mx-auto max-w-[1176px]"><p className="rev-kicker">A financial read you can inspect</p><div className="mt-5 grid gap-8 md:grid-cols-2"><h2 className="[font-family:var(--font-instrument-serif)] text-4xl font-normal leading-tight md:text-5xl">Three sources.<br />One explainable read.</h2><p className="max-w-lg text-sm leading-8 text-[color:var(--text-muted)]">Provider totals rarely explain who consumed the spend. Internal ledgers can miss events. REVORY puts the evidence in the same period and keeps ambiguity visible, so you can decide what deserves investigation.</p></div><div className="mt-10 grid gap-4 md:grid-cols-3">{[["01", "Bring a closed period", "Upload one export from each source. Preview columns and excluded rows before storing evidence."], ["02", "Confirm customer identity", "Review exact customer and project IDs. Shared or conflicting projects keep their uncertainty."], ["03", "Follow each difference", "Open the calculation, source records and limitations. Take an evidence report back to your team."]].map(([step, title, copy]) => <div key={step} className="rev-marketing-card rounded-[26px] p-6"><p className="text-xs text-[color:var(--accent)]">{step}</p><h3 className="mt-5 text-base font-bold">{title}</h3><p className="mt-3 text-sm leading-7 text-[color:var(--text-muted)]">{copy}</p></div>)}</div></div></section>
    <section className="mx-auto grid max-w-[1240px] gap-12 px-5 py-20 md:px-8 lg:grid-cols-2"><div><p className="rev-kicker">Start with one useful read</p><h2 className="mt-5 [font-family:var(--font-instrument-serif)] text-4xl font-normal leading-tight md:text-5xl">A scan with a defined scope.<br />An answer with a paper trail.</h2><p className="mt-6 max-w-lg text-sm leading-8 text-[color:var(--text-muted)]">The first scan focuses on reported AI spend without customer attribution and usage differences between your ledger and provider. Revenue stays visible as context. Monitoring follows paid customer validation.</p><Link className="mt-6 inline-block text-sm font-semibold text-[color:var(--accent)]" href="/demo">Explore the full synthetic report →</Link></div><div className="rev-shell-panel rounded-[30px] p-7 md:p-8"><p className="rev-kicker">Integrity Scan · Test offer</p><div className="mt-5 flex items-end gap-3"><p className="text-5xl font-semibold tracking-[-0.05em]">$99</p><p className="pb-1 text-sm text-[color:var(--text-muted)]">USD · one time</p></div><p className="mt-3 text-xs leading-6 text-[color:var(--text-subtle)]">Price hypothesis in development. One report for one closed period.</p><ul className="mt-7 space-y-4 text-sm text-[color:var(--text-muted)]">{["Three reviewed source exports", "Customer identity and attribution coverage", "Usage differences with calculations and evidence", "JSON evidence report and CSV findings"].map((item) => <li key={item} className="flex gap-3"><span className="text-[color:var(--accent)]">✓</span>{item}</li>)}</ul><Link className="rev-button-primary mt-8 w-full" href="/start">Check your data & start ↗</Link><p className="mt-4 text-center text-xs text-[color:var(--text-subtle)]">One-time test purchase · No subscription starts.</p></div></section>
    <AiMarketingFooter />
  </main>;
}
