import { getAiValidationReview } from "@/services/ai-integrity/validation-review";

const labels: Record<string, string> = { CONFIRMED_DIFFERENCE: "Supported difference", EXPECTED_DIFFERENCE: "Expected difference", FALSE_POSITIVE: "False positive", INSUFFICIENT_EVIDENCE: "Insufficient evidence", USEFUL: "Useful", PARTLY_USEFUL: "Partly useful", NOT_USEFUL: "Not useful" };
export async function AiValidationReviewSummary({ workspaceId, snapshotId, fingerprint }: { workspaceId: string; snapshotId: string; fingerprint?: string }) {
  const review = await getAiValidationReview(workspaceId, snapshotId); if (!review) return null;
  const summary = review.summary;
  const current = fingerprint ? summary.currentFindings.find((event) => event.fingerprint === fingerprint) : null;
  const history = fingerprint ? review.events.filter((event) => event.fingerprint === fingerprint) : review.events;
  return <section className="rev-shell-panel space-y-4 rounded-[26px] p-5 md:p-7"><div className="flex flex-wrap justify-between gap-3"><h2 className="text-lg font-semibold">{fingerprint ? "Review history" : "Source review progress"}</h2><a className="text-xs text-[color:var(--accent)]" href={`/api/ai-integrity/scans/${snapshotId}/reviews`}>Download review history JSON ↗</a></div>
    {fingerprint ? <p className="text-sm text-[color:var(--text-muted)]">Current conclusion: {current ? labels[current.disposition!] : "Not reviewed"}</p> : <><div className="grid gap-3 sm:grid-cols-3">{[["Findings reviewed", `${summary.reviewedFindings} / ${summary.totalFindings}`], ["Still undecided", String(summary.insufficientEvidence + summary.unreviewedFindings)], ["False positives / conclusive reviews", `${summary.falsePositives} / ${summary.conclusivelyReviewed}`]].map(([label, value]) => <div key={label} className="rounded-xl border border-[color:var(--border)] p-4"><p className="text-xs text-[color:var(--text-muted)]">{label}</p><p className="mt-3 text-lg font-semibold">{value}</p></div>)}</div><p className="text-xs leading-6 text-[color:var(--text-muted)]">{summary.falsePositiveRateBps === null ? "False-positive rate is not measured yet." : `False-positive rate among conclusively reviewed findings: ${(summary.falsePositiveRateBps / 100).toFixed(2)}%.`} Unreviewed and insufficient-evidence findings remain outside that denominator. Confirmed differences do not establish monetary loss.</p><p className="text-xs leading-6 text-[color:var(--text-muted)]">Report usefulness: {summary.reportReview ? `${labels[summary.reportReview.usefulness!]} · ${summary.reportReview.preparationMinutes} preparation minutes · ${summary.reportReview.assistanceRequired ? "assistance needed" : "no assistance reported"}` : "Not recorded"}.</p></>}
    <p className="text-[11px] leading-6 text-[color:var(--text-subtle)]">Synthetic rehearsal only. These records count as zero real paid participants and do not validate the market or pricing.</p>
    {history.length ? <details><summary className="cursor-pointer text-xs text-[color:var(--accent)]">Inspect {history.length} saved review versions</summary><div className="mt-4 max-h-72 space-y-3 overflow-y-auto">{history.map((event) => <div key={event.id} className="rounded-xl border border-[color:var(--border)] p-4"><p className="text-xs font-semibold">Version {event.revision} · {labels[event.disposition ?? event.usefulness ?? ""]} · {event.createdAt.slice(0, 16)} UTC</p><p className="mt-2 whitespace-pre-wrap break-words text-xs leading-6 text-[color:var(--text-muted)] [font-family:var(--font-dm-sans)]">{event.comment}</p></div>)}</div></details> : <p className="text-xs text-[color:var(--text-muted)]">No review recorded. The report findings remain unchanged.</p>}
  </section>;
}
