"use server";

import { revalidatePath } from "next/cache";

import { prisma } from "@/db/prisma";
import { getAppContext } from "@/services/app/get-app-context";

export async function updateRetentionAction(formData:FormData){const context=await getAppContext();if(!context)return;const days=Number(formData.get("retentionDays"));if(![30,90,180,365].includes(days))return;await prisma.$transaction([prisma.workspaceDataSettings.upsert({where:{workspaceId:context.workspace.id},create:{workspaceId:context.workspace.id,retentionDays:days},update:{retentionDays:days}}),prisma.workspaceAuditEvent.create({data:{workspaceId:context.workspace.id,actorUserId:context.user.id,action:"RETENTION_UPDATED",metadataJson:{retentionDays:days}}})]);revalidatePath("/app/settings")}
export async function updateDigestAction(formData:FormData){const context=await getAppContext();if(!context)return;const enabled=formData.get("enabled")==="on";await prisma.$transaction([prisma.quoteRecoveryDigestPreference.upsert({where:{workspaceId:context.workspace.id},create:{workspaceId:context.workspace.id,enabled},update:{enabled}}),prisma.workspaceAuditEvent.create({data:{workspaceId:context.workspace.id,actorUserId:context.user.id,action:"DIGEST_PREFERENCE_UPDATED",metadataJson:{enabled}}})]);revalidatePath("/app/settings")}
export async function deleteAnalysisDataAction(formData:FormData){const context=await getAppContext();if(!context)return;if(formData.get("confirmation")!=="DELETE REVORY DATA")return;const workspaceId=context.workspace.id;await prisma.$transaction(async(tx)=>{await tx.revenueIntelligenceSnapshot.deleteMany({where:{workspaceId}});await tx.revenueRealizationFinding.deleteMany({where:{workspaceId}});await tx.quoteRecoveryFinding.deleteMany({where:{workspaceId}});await tx.quoteRecoveryAnalysisRun.deleteMany({where:{workspaceId}});await tx.savedCanonicalMapping.deleteMany({where:{workspaceId}});await tx.canonicalImportSession.deleteMany({where:{workspaceId}});await tx.workspaceDataSettings.upsert({where:{workspaceId},create:{workspaceId,lastAnalysisDeletedAt:new Date()},update:{lastAnalysisDeletedAt:new Date()}});await tx.workspaceAuditEvent.create({data:{workspaceId,actorUserId:context.user.id,action:"ANALYSIS_DATA_DELETED",metadataJson:{scope:"canonical imports, mappings, quote and realization findings, analysis runs and intelligence snapshots"}}})});console.log(JSON.stringify({level:"info",message:"analysis_data_deleted",workspaceId}));revalidatePath("/app/dashboard");revalidatePath("/app/history");revalidatePath("/app/settings")}
