import { buildOperationalSurface } from "@/services/operations/build-operational-surface";
import {
  buildBlockedOperationalState,
  buildOperationalStateSummary,
  buildPreparedOperationalState,
  buildReadyOperationalState,
} from "@/services/operations/build-operational-state";

const now = new Date("2026-03-22T15:00:00.000Z");

const surface = await buildOperationalSurface({
  atRisk: {
    atRiskCount: 2,
    attentionNowCount: 1,
    blockedContactCount: 1,
    generatedAt: now,
    items: [
      {
        appointmentId: "appointment-tight-window",
        attentionLevel: "attention_now",
        clientEmail: null,
        clientId: "client-1",
        clientName: "Ashley Monroe",
        estimatedRevenue: 320,
        hoursUntilAppointment: 3,
        operationalState: buildReadyOperationalState(),
        primaryReasonCode: "same_day_tight_window",
        providerName: "Dr. Rivera",
        reasons: [
          {
            attentionLevel: "attention_now",
            code: "same_day_tight_window",
            description: "The appointment is approaching with very little time buffer.",
            label: "Same-day tight window",
          },
        ],
        scheduledAt: new Date("2026-03-22T18:00:00.000Z"),
        serviceName: "Laser Consultation",
        status: "SCHEDULED",
      },
      {
        appointmentId: "appointment-watch",
        attentionLevel: "watchlist",
        clientEmail: null,
        clientId: "client-2",
        clientName: "Bianca Hart",
        estimatedRevenue: 180,
        hoursUntilAppointment: 30,
        operationalState: buildPreparedOperationalState(),
        primaryReasonCode: "confirmation_blocked_missing_email",
        providerName: "Dr. Chen",
        reasons: [
          {
            attentionLevel: "watchlist",
            code: "confirmation_blocked_missing_email",
            description: "Inside confirmation window without usable email.",
            label: "Confirmation blocked by missing email",
          },
        ],
        scheduledAt: new Date("2026-03-23T21:00:00.000Z"),
        serviceName: "Skin Reset",
        status: "SCHEDULED",
      },
    ],
    policy: {
      confirmationWindowHours: 48,
      immediateWindowHours: 6,
      reminderWindowHours: 24,
    },
    stateSummary: buildOperationalStateSummary({
      classifiedItemsCount: 2,
      states: [buildReadyOperationalState(), buildPreparedOperationalState()],
      totalBaselineCount: 4,
    }),
    tightWindowCount: 1,
    totalFutureScheduledAppointments: 4,
    watchlistCount: 1,
  },
  confirmation: {
    blockedMissingEmailCount: 1,
    channel: "EMAIL",
    generatedAt: now,
    items: [
      {
        appointmentId: "appointment-watch",
        clientEmail: null,
        clientId: "client-2",
        clientName: "Bianca Hart",
        confirmationState: "blocked_missing_email",
        estimatedRevenue: 180,
        hoursUntilAppointment: 30,
        operationalState: buildBlockedOperationalState(["missing_patient_email"]),
        providerName: "Dr. Chen",
        reasonCode: "inside_confirmation_window_missing_email",
        requiresAttention: true,
        scheduledAt: new Date("2026-03-23T21:00:00.000Z"),
        serviceName: "Skin Reset",
        status: "SCHEDULED",
      },
    ],
    needsAttentionCount: 1,
    readyForConfirmationCount: 0,
    scheduledLaterCount: 1,
    stateSummary: buildOperationalStateSummary({
      classifiedItemsCount: 1,
      states: [buildBlockedOperationalState(["missing_patient_email"])],
      totalBaselineCount: 4,
    }),
    totalFutureScheduledAppointments: 4,
    windowEndsAt: new Date("2026-03-24T15:00:00.000Z"),
    windowHours: 48,
  },
  hasAppointmentBase: true,
  recovery: {
    blockedMissingEmailCount: 0,
    canceledOpportunityCount: 1,
    channel: "EMAIL",
    generatedAt: now,
    items: [
      {
        appointmentId: "appointment-canceled-open",
        clientEmail: "client@example.com",
        clientId: "client-3",
        clientName: "Mila Stone",
        disruptionDate: new Date("2026-03-21T14:00:00.000Z"),
        estimatedRevenue: 260,
        operationalState: buildReadyOperationalState(),
        providerName: "Dr. Rivera",
        reasons: [
          {
            code: "canceled_without_rebooking",
            description: "The appointment was canceled and there is no later visit.",
            label: "Canceled without rebooking",
          },
        ],
        recoveryState: "ready_for_recovery",
        serviceName: "Injectables",
        status: "CANCELED",
      },
    ],
    noShowOpportunityCount: 0,
    opportunityCount: 1,
    readyForRecoveryCount: 1,
    stateSummary: buildOperationalStateSummary({
      classifiedItemsCount: 1,
      states: [buildReadyOperationalState()],
      totalBaselineCount: 1,
    }),
    totalDisruptedAppointmentsInWindow: 1,
    windowDays: 14,
    windowEndsAt: new Date("2026-04-05T15:00:00.000Z"),
    windowStartsAt: new Date("2026-03-08T15:00:00.000Z"),
  },
  reminder: {
    blockedMissingEmailCount: 0,
    channel: "EMAIL",
    generatedAt: now,
    items: [
      {
        appointmentId: "appointment-reminder-ready",
        clientEmail: "client@example.com",
        clientId: "client-4",
        clientName: "Olivia Reed",
        estimatedRevenue: 140,
        hoursUntilAppointment: 12,
        operationalState: buildReadyOperationalState(),
        providerName: "Dr. Kent",
        reasonCode: "inside_reminder_window",
        reminderState: "ready_for_reminder",
        requiresAttention: true,
        scheduledAt: new Date("2026-03-23T03:00:00.000Z"),
        serviceName: "Post-Treatment Check",
        status: "SCHEDULED",
      },
    ],
    needsAttentionCount: 1,
    readyForReminderCount: 1,
    scheduledLaterCount: 1,
    stateSummary: buildOperationalStateSummary({
      classifiedItemsCount: 1,
      states: [buildReadyOperationalState()],
      totalBaselineCount: 4,
    }),
    totalFutureScheduledAppointments: 4,
    windowEndsAt: new Date("2026-03-23T15:00:00.000Z"),
    windowHours: 24,
  },
  reviewRequest: {
    blockedMissingEmailCount: 0,
    blockedMissingReviewsUrlCount: 1,
    channel: "EMAIL",
    eligibleCount: 1,
    generatedAt: now,
    items: [
      {
        appointmentId: "appointment-review-ready",
        clientEmail: "client@example.com",
        clientId: "client-5",
        clientName: "Emma Vale",
        completedAt: new Date("2026-03-21T10:00:00.000Z"),
        estimatedRevenue: 220,
        googleReviewsUrl: "https://g.page/example",
        operationalState: buildReadyOperationalState(),
        providerName: "Dr. Kent",
        reasons: [
          {
            code: "completed_recently",
            description: "Completed recently.",
            label: "Completed recently",
          },
        ],
        reviewEligibilityState: "eligible_for_review_request",
        serviceName: "Hydrafacial",
        status: "COMPLETED",
      },
      {
        appointmentId: "appointment-review-blocked",
        clientEmail: "client2@example.com",
        clientId: "client-6",
        clientName: "Sofia Lane",
        completedAt: new Date("2026-03-20T12:00:00.000Z"),
        estimatedRevenue: 190,
        googleReviewsUrl: null,
        operationalState: buildBlockedOperationalState(["missing_reviews_destination"]),
        providerName: "Dr. Chen",
        reasons: [
          {
            code: "completed_recently",
            description: "Completed recently.",
            label: "Completed recently",
          },
          {
            code: "blocked_missing_reviews_url",
            description: "No reviews destination configured.",
            label: "Review request blocked by missing reviews destination",
          },
        ],
        reviewEligibilityState: "blocked_missing_reviews_url",
        serviceName: "Botox Review",
        status: "COMPLETED",
      },
    ],
    stateSummary: buildOperationalStateSummary({
      classifiedItemsCount: 2,
      states: [
        buildReadyOperationalState(),
        buildBlockedOperationalState(["missing_reviews_destination"]),
      ],
      totalBaselineCount: 2,
    }),
    totalCompletedAppointmentsInWindow: 2,
    windowDays: 7,
    windowEndsAt: now,
    windowStartsAt: new Date("2026-03-15T15:00:00.000Z"),
  },
});

console.log(
  JSON.stringify(
    {
      blockedCount: surface.blockedCount,
      cardOrder: surface.categoryCards.map(
        (card) => `${card.key}:${card.count}:${card.readinessLabel}`,
      ),
      hasLiveSignals: surface.hasLiveSignals,
      needsAttentionNowCount: surface.needsAttentionNowCount,
      priorityHeadline: surface.prioritySummary.headline,
      readinessSummary: surface.readinessSummary,
      priorityItems: surface.priorityItems.map((item) => ({
        blockedReason: item.blockedReason,
        category: item.categoryKey,
        id: item.id,
        readiness: item.readinessLabel,
        state: item.stateLabel,
      })),
      templatePreviews: surface.templatePreviews.map((preview) => ({
        blockedReason: preview.blockedReason,
        key: preview.key,
        liveItemCount: preview.liveItemCount,
        mode: preview.previewMode,
        outreachState: preview.outreachStateLabel,
        placeholders: preview.placeholders.map((placeholder) => placeholder.token),
        suggestedNextStep: preview.suggestedNextStep,
        title: preview.title,
      })),
    },
    null,
    2,
  ),
);
