import { REVORY_LEGAL } from "@/content/revory-legal";

export type LegalLocale = "en" | "pt-BR";

export type LegalSection = {
  body: readonly string[];
  title: string;
};

export type LegalDocument = {
  description: string;
  kicker: string;
  sections: readonly LegalSection[];
  title: string;
};

const company = `${REVORY_LEGAL.legalName}, CNPJ ${REVORY_LEGAL.taxId}`;

export const termsDocuments: Record<LegalLocale, LegalDocument> = {
  en: {
    kicker: "Terms of Service",
    title: "Terms for using REVORY.",
    description: `These Terms are an agreement between you and ${company}, doing business through the REVORY product.`,
    sections: [
      { title: "1. Provider and acceptance", body: [`REVORY is provided by ${company}, at ${REVORY_LEGAL.address}. By creating an account, buying an offer or using the service, you accept these Terms. The Privacy Notice and Cancellation and Refund Policy are incorporated by reference.`] },
      { title: "2. Definitions", body: ["“Customer” means the business accepting these Terms. “Authorized User” means a person the Customer permits to use its workspace. “Customer Data” means data submitted by or for the Customer. “Output” means a REVORY finding, report, export or recommendation. “Order” means the checkout or signed order identifying an offer, price and billing cadence."] },
      { title: "3. Business use and authority", body: ["REVORY is offered primarily for business use. You represent that you are legally able to bind the Customer and are authorized to submit its data. Mandatory rights that legally apply to an individual consumer are not waived."] },
      { title: "4. Service scope", body: ["REVORY provides narrow, self-service revenue-leak intelligence for high-ticket service businesses. It is not a CRM, inbox, autonomous follow-up agent, field-service, scheduling, accounting, job-costing, project-management, legal, tax or financial-advisory service."] },
      { title: "5. Accounts and workspaces", body: ["You must provide accurate information, protect credentials, maintain current recovery methods and promptly remove unauthorized access. Customer is responsible for its Authorized Users. Each workspace must remain logically separate and may be used only for data the Customer is authorized to process."] },
      { title: "6. Authorized use", body: ["We grant a limited, non-exclusive, non-transferable and revocable right to use the purchased service during its access period. You may not resell access or use REVORY to build a competing product except under a written agreement."] },
      { title: "7. Customer Data license", body: ["Customer retains its rights in Customer Data and grants Ametrine Labs a limited license to host, copy, transform and otherwise process that data only to provide, secure, support and improve the reliability of the service, follow documented instructions, prevent abuse and comply with law."] },
      { title: "8. Data processing roles", body: ["Ametrine Labs is generally a processor/operator for exports containing the Customer’s end-customer records and acts on Customer instructions. It is a controller for account, authentication, billing, security, support and service-operations data. The DPA applies where Ametrine Labs processes personal data for Customer."] },
      { title: "9. Bounded AI", body: ["Optional AI may assist with uncertain mappings, classifications, explanations or narrowly scoped text. Deterministic rules remain authoritative for financial findings. AI never approves an import, silently links records, sends customer communications or replaces human review. Depending on the enabled feature, minimized metadata or limited user-provided context may be sent to the disclosed AI provider."] },
      { title: "10. Acceptable use", body: ["Do not upload unlawful data, malware, secrets, payment-card data, health records or data outside the supported purpose; probe or bypass security; interfere with other tenants; scrape, reverse engineer or overload the service; impersonate others; or use Output for unlawful discrimination, spam or automated adverse decisions."] },
      { title: "11. Confidentiality", body: ["Each party will protect the other party’s non-public business, technical and personal information with reasonable care, use it only for the agreement and disclose it only to personnel and providers who need it and are bound to protect it. Duties do not cover information lawfully public, independently developed or rightfully received without restriction. Required disclosures will be limited and, when lawful, notified in advance."] },
      { title: "12. Third-party services", body: ["Hosting, database, email, billing, authentication and optional AI depend on third-party providers identified in the Subprocessor Notice. Their independent services and external websites are governed by their own terms. We remain responsible for our contractual obligations and do not control provider-wide outages."] },
      { title: "13. One-time Audits", body: ["A one-time Quote Recovery Audit includes one supported analysis run unless the Order says otherwise. Reviewing or uploading files alone does not consume it. Consumption begins when Customer confirms the reviewed mapping and the one-time use, and REVORY commits the import and creates the analysis read. A later re-run requires another entitlement or recurring plan."] },
      { title: "14. Subscriptions, fees and taxes", body: ["Subscriptions renew automatically at the cadence and price shown at checkout until canceled. Customer authorizes the disclosed recurring charges. Fees exclude applicable taxes unless checkout says otherwise. Customer is responsible for lawful taxes, and failed payment may suspend access after reasonable notice where practicable."] },
      { title: "15. Cancellation and refunds", body: ["Cancellation, withdrawal and refund eligibility follow the Cancellation and Refund Policy and mandatory law. Canceling a subscription normally prevents the next renewal and leaves access through the paid period. One-time service commencement is defined in Section 13."] },
      { title: "16. Availability and support", body: ["We use commercially reasonable efforts to operate and support REVORY, but do not guarantee uninterrupted or error-free availability. Planned maintenance, internet failures and third-party events may affect access. Support is available through the published support channel."] },
      { title: "17. Beta, preview and roadmap", body: ["Features marked beta, preview, gated, future or roadmap may be incomplete, changed or withdrawn and are not part of a paid Order unless expressly listed there. Change orders, invoices, underbilling, margin and Revenue Realization capabilities are not sellable merely because they appear in product materials."] },
      { title: "18. No guaranteed outcome", body: ["Outputs are decision-support signals, not guaranteed revenue, recovery, loss, profit, margin, accounting treatment or business result. Zero findings does not prove that no issue exists. Customer must verify source records and decide whether and how to act."] },
      { title: "19. Customer verification", body: ["Customer is responsible for data accuracy, mapping approval, record matching, business decisions and review by appropriate professionals. REVORY preserves ambiguity rather than inventing links. Output must not be treated as audited financial statements or professional advice."] },
      { title: "20. REVORY intellectual property", body: ["Ametrine Labs and its licensors own REVORY, its software, designs, methods, documentation and trademarks. Except for the limited use right, no intellectual-property right is transferred. Lawful interoperability rights that cannot be excluded remain unaffected."] },
      { title: "21. Customer materials", body: ["Customer owns Customer Data and its pre-existing materials. Customer represents that it has the rights and lawful basis needed for Ametrine Labs to process them under these Terms and the DPA."] },
      { title: "22. Feedback", body: ["If Customer voluntarily provides feedback, Ametrine Labs may use it without restriction or payment, provided it does not identify Customer or disclose Customer Confidential Information without permission."] },
      { title: "23. Suspension and cure", body: ["We may suspend the minimum access necessary to address nonpayment, a material breach, unlawful use, credible security risk or harm to the service. When reasonably possible, we will give notice and an opportunity to cure. Emergency protective action may occur first."] },
      { title: "24. Termination", body: ["Either party may terminate for an uncured material breach after reasonable written notice, or immediately for fraud, illegality or insolvency where permitted. Customer may stop using REVORY at any time; subscription cancellation is handled under Section 15."] },
      { title: "25. Export and deletion", body: ["Authorized workspace users can export stored workspace data and delete supported analysis data in Settings. Configured analysis retention is 30, 90, 180 or 365 days and defaults to 365 days. Account closure or deletion beyond the self-service controls must be requested through support. Security, billing, legal and backup records may remain where necessary and lawful; we do not promise an unimplemented automatic post-cancellation deletion deadline."] },
      { title: "26. Warranties and disclaimers", body: ["Each party warrants it has authority to enter the agreement. To the maximum extent permitted by law, REVORY is provided “as is” and “as available,” and implied warranties of merchantability, fitness, non-infringement and uninterrupted operation are disclaimed. Mandatory warranties are not excluded."] },
      { title: "27. Excluded damages", body: ["To the maximum extent permitted by law, neither party is liable for indirect, incidental, special, punitive or consequential damages, or lost profits, revenue, goodwill or data, arising from the agreement, even if advised of the possibility. This exclusion is subject to Section 29."] },
      { title: "28. Liability cap", body: ["Except under Section 29, each party’s total aggregate liability arising from the agreement will not exceed fees paid or payable for the service during the 12 months before the event giving rise to liability. For a one-time Audit with no recurring fees, the cap is the amount paid for that Audit."] },
      { title: "29. Liability exceptions", body: ["Sections 27 and 28 do not limit liability to the extent it results from fraud or willful misconduct, breach of confidentiality, infringement or misappropriation of the other party’s intellectual property, Customer’s unlawful Customer Data or instructions, indemnity obligations under Section 30, or liability that applicable law does not permit the parties to limit."] },
      { title: "30. Indemnity", body: ["Customer will defend and indemnify Ametrine Labs against third-party claims caused by Customer’s unlawful Customer Data, instructions or use. Ametrine Labs will defend and indemnify Customer against a third-party claim that the unmodified paid service infringes Brazilian intellectual-property rights, excluding combinations, Customer Data and unauthorized use. The protected party must promptly notify, permit control of the defense and reasonably cooperate. Settlements may not admit fault or impose non-monetary obligations without consent."] },
      { title: "31. Force majeure", body: ["Neither party is liable for delay caused by events beyond reasonable control, including utility, internet, cloud-provider, labor, civil, governmental or natural events, except payment obligations for services already provided. The affected party will use reasonable efforts to mitigate."] },
      { title: "32. Changes to service or terms", body: ["We may improve the service and update these Terms. Material legal changes will be notified through the product, email or website before they take effect when reasonably practicable. Continued use after the effective date constitutes acceptance where lawful; material changes may require renewed electronic acceptance."] },
      { title: "33. Notices", body: [`Legal notices to Ametrine Labs must be sent to ${REVORY_LEGAL.supportEmail}. We may send notices to the account email or display them in REVORY. Operational support messages are not formal legal notices unless clearly identified.`] },
      { title: "34. Assignment", body: ["Neither party may assign the agreement without the other’s consent, except to an affiliate or in connection with a merger, reorganization or sale of substantially all relevant assets, provided the assignee assumes the obligations. An unlawful assignment is void."] },
      { title: "35. Severability and waiver", body: ["If a provision is unenforceable, it will be limited to the minimum necessary and the remainder continues. Failure to enforce a provision is not a waiver, and a waiver must be written and specific."] },
      { title: "36. Entire agreement and precedence", body: ["These Terms, the applicable Order, DPA, Privacy Notice and Refund Policy form the agreement. A signed Order controls commercial specifics; the DPA controls processing of Customer Personal Data; then these Terms control. Customer purchase-order boilerplate does not amend the agreement."] },
      { title: "37. Survival", body: ["Provisions concerning payment, confidentiality, intellectual property, data responsibilities, disclaimers, liability, indemnity, dispute resolution and provisions that by nature should survive will remain effective after termination."] },
      { title: "38. Electronic acceptance", body: ["Clicking the account-creation or checkout action, or otherwise electronically accepting an Order, has the same effect as a signature to the extent permitted by law. REVORY may retain the user, workspace, document versions, event, context and timestamp as acceptance evidence."] },
      { title: "39. Governing law, forum and contact", body: [`Brazilian law governs, without regard to conflict rules. Courts located in Sao Paulo, SP, Brazil have jurisdiction, except for a mandatory consumer forum, data-protection authority competence or other non-waivable right. Contact ${REVORY_LEGAL.supportEmail}.`] },
    ],
  },
  "pt-BR": {
    kicker: "Termos de Uso",
    title: "Termos para usar o REVORY.",
    description: `Estes Termos formam um contrato entre você e ${company}, que oferece o produto REVORY.`,
    sections: [
      { title: "1. Fornecedor e aceite", body: [`O REVORY é fornecido por ${company}, com sede em ${REVORY_LEGAL.address}. Ao criar conta, comprar uma oferta ou usar o serviço, você aceita estes Termos. O Aviso de Privacidade e a Política de Cancelamento e Reembolso fazem parte deles.`] },
      { title: "2. Definições", body: ["“Cliente” é a empresa que aceita estes Termos. “Usuário Autorizado” é quem o Cliente permite usar o workspace. “Dados do Cliente” são os dados enviados pelo Cliente ou em seu nome. “Resultado” é um achado, relatório, exportação ou recomendação do REVORY. “Pedido” é o checkout ou pedido assinado com oferta, preço e periodicidade."] },
      { title: "3. Uso empresarial e poderes", body: ["O REVORY é oferecido principalmente para uso empresarial. Você declara poder vincular o Cliente e estar autorizado a enviar os dados. Direitos obrigatórios aplicáveis a consumidor pessoa física não são afastados."] },
      { title: "4. Escopo do serviço", body: ["O REVORY oferece inteligência de vazamento de receita, restrita e self-service, para empresas de serviços high-ticket. Não é CRM, caixa de entrada, agente autônomo de follow-up, sistema de campo, agenda, contabilidade, job costing, gestão de projetos ou consultoria jurídica, tributária ou financeira."] },
      { title: "5. Contas e workspaces", body: ["Você deve fornecer informações corretas, proteger credenciais, manter métodos de recuperação e remover acessos indevidos. O Cliente responde pelos Usuários Autorizados. Cada workspace deve permanecer separado e conter apenas dados cujo tratamento seja autorizado."] },
      { title: "6. Uso autorizado", body: ["Concedemos direito limitado, não exclusivo, intransferível e revogável de uso do serviço comprado durante o período de acesso. É proibido revender o acesso ou usar o REVORY para criar produto concorrente sem acordo escrito."] },
      { title: "7. Licença sobre Dados do Cliente", body: ["O Cliente mantém seus direitos e concede à Ametrine Labs licença limitada para hospedar, copiar, transformar e tratar os dados apenas para fornecer, proteger, dar suporte e melhorar a confiabilidade do serviço, seguir instruções documentadas, prevenir abuso e cumprir a lei."] },
      { title: "8. Papéis no tratamento", body: ["A Ametrine Labs é, em regra, operadora dos arquivos com registros de clientes finais enviados pelo Cliente e atua conforme suas instruções. É controladora dos dados de conta, autenticação, cobrança, segurança, suporte e operação. O DPA se aplica ao tratamento de dados pessoais em nome do Cliente."] },
      { title: "9. IA limitada", body: ["IA opcional pode auxiliar em mapeamentos incertos, classificações, explicações ou textos restritos. Regras determinísticas são a autoridade para achados financeiros. A IA não aprova importação, vincula registros silenciosamente, envia comunicação nem substitui revisão humana. Conforme o recurso, metadados minimizados ou contexto limitado fornecido pelo usuário podem chegar ao provedor divulgado."] },
      { title: "10. Uso aceitável", body: ["Não envie dados ilícitos, malware, segredos, dados de cartão, saúde ou fora da finalidade; não burle segurança, afete outros tenants, faça scraping, engenharia reversa ou sobrecarga; não se passe por terceiros nem use Resultados para discriminação ilegal, spam ou decisões adversas automatizadas."] },
      { title: "11. Confidencialidade", body: ["Cada parte protegerá informações não públicas da outra com cuidado razoável, usando-as apenas para o contrato e compartilhando-as somente com quem precise e esteja obrigado a protegê-las. Não se aplica a informação pública licitamente, desenvolvida de forma independente ou recebida sem restrição. Divulgação legal obrigatória será limitada e, quando permitido, avisada."] },
      { title: "12. Terceiros", body: ["Hospedagem, banco, e-mail, cobrança, autenticação e IA opcional dependem dos provedores do Aviso de Suboperadores. Serviços independentes seguem seus próprios termos. Continuamos responsáveis por nossas obrigações, mas não controlamos indisponibilidades gerais do provedor."] },
      { title: "13. Auditorias avulsas", body: ["Uma Quote Recovery Audit avulsa inclui uma leitura, salvo disposição diferente no Pedido. Revisar ou anexar arquivos não a consome. O consumo começa quando o Cliente confirma o mapeamento revisado e o uso avulso, e o REVORY efetiva a importação e cria a leitura. Nova execução exige outro direito ou plano recorrente."] },
      { title: "14. Assinaturas, valores e tributos", body: ["Assinaturas renovam automaticamente na periodicidade e pelo preço exibidos no checkout até o cancelamento. O Cliente autoriza cobranças recorrentes informadas. Valores não incluem tributos aplicáveis, salvo indicação contrária. Falha de pagamento pode suspender o acesso após aviso razoável quando viável."] },
      { title: "15. Cancelamento e reembolso", body: ["Elegibilidade segue a Política de Cancelamento e Reembolso e a lei obrigatória. Cancelar normalmente impede a próxima renovação e mantém acesso até o fim do período pago. O início do serviço avulso é o definido na Seção 13."] },
      { title: "16. Disponibilidade e suporte", body: ["Empregamos esforços comercialmente razoáveis, sem garantir operação ininterrupta ou sem erros. Manutenção, internet e eventos de terceiros podem afetar o acesso. O suporte usa o canal publicado."] },
      { title: "17. Beta, preview e roadmap", body: ["Recursos beta, preview, gated, futuros ou de roadmap podem mudar ou ser removidos e não integram o Pedido pago salvo listagem expressa. Change orders, invoices, underbilling, margin e Revenue Realization não se tornam vendáveis por aparecerem em materiais."] },
      { title: "18. Sem resultado garantido", body: ["Resultados apoiam decisão; não garantem receita, recuperação, perda, lucro, margem, tratamento contábil ou resultado empresarial. Zero achados não prova inexistência de problema. O Cliente verifica os registros e decide como agir."] },
      { title: "19. Verificação do Cliente", body: ["O Cliente responde pela exatidão, aprovação do mapeamento, correspondência de registros, decisões e revisão profissional apropriada. O REVORY preserva ambiguidade em vez de inventar vínculos. Resultados não são demonstrações financeiras auditadas nem aconselhamento profissional."] },
      { title: "20. Propriedade intelectual do REVORY", body: ["A Ametrine Labs e seus licenciantes detêm software, design, métodos, documentação e marcas. Nenhum direito além do uso limitado é transferido. Direitos legais irrenunciáveis de interoperabilidade permanecem."] },
      { title: "21. Materiais do Cliente", body: ["O Cliente detém seus Dados e materiais preexistentes e declara possuir direitos e base legal necessários para o tratamento conforme estes Termos e o DPA."] },
      { title: "22. Feedback", body: ["Ametrine Labs pode usar feedback voluntário sem restrição ou pagamento, desde que não identifique o Cliente nem divulgue Informação Confidencial sem autorização."] },
      { title: "23. Suspensão e cura", body: ["Podemos suspender apenas o necessário por inadimplência, violação material, uso ilícito, risco de segurança ou dano. Quando razoável, haverá aviso e chance de correção; proteção emergencial pode ocorrer antes."] },
      { title: "24. Rescisão", body: ["Qualquer parte pode rescindir por violação material não sanada após aviso razoável, ou imediatamente por fraude, ilicitude ou insolvência quando permitido. O Cliente pode parar de usar; cancelamento de assinatura segue a Seção 15."] },
      { title: "25. Exportação e exclusão", body: ["Usuários autorizados podem exportar dados do workspace e excluir dados de análise suportados em Configurações. A retenção configurável é 30, 90, 180 ou 365 dias, padrão 365. Encerramento da conta ou exclusão além do self-service deve ser solicitado ao suporte. Registros de segurança, cobrança, legais e backup podem permanecer quando necessários e lícitos; não prometemos prazo automático pós-cancelamento que não esteja implementado."] },
      { title: "26. Garantias e ressalvas", body: ["Cada parte garante ter poderes para contratar. Na extensão legal, o REVORY é oferecido “como está” e “conforme disponível”, sem garantias implícitas de adequação, comercialização, não violação ou operação contínua. Garantias obrigatórias permanecem."] },
      { title: "27. Danos excluídos", body: ["Na extensão legal, nenhuma parte responde por danos indiretos, incidentais, especiais, punitivos ou consequenciais, nem por perda de lucro, receita, reputação ou dados, mesmo avisada da possibilidade, sujeito à Seção 29."] },
      { title: "28. Limite de responsabilidade", body: ["Exceto na Seção 29, a responsabilidade agregada de cada parte não excederá os valores pagos ou devidos nos 12 meses anteriores ao fato. Para Auditoria avulsa sem recorrência, o limite é o valor pago por ela."] },
      { title: "29. Exceções ao limite", body: ["As Seções 27 e 28 não limitam responsabilidade por fraude ou dolo, violação de confidencialidade, violação da propriedade intelectual da outra parte, Dados ou instruções ilícitas do Cliente, indenização da Seção 30 ou responsabilidade legalmente ilimitável."] },
      { title: "30. Indenização", body: ["O Cliente defenderá e indenizará Ametrine Labs por reclamação de terceiro causada por Dados, instruções ou uso ilícito. Ametrine Labs defenderá e indenizará o Cliente por reclamação de que o serviço pago inalterado viola propriedade intelectual brasileira, excluídas combinações, Dados e uso não autorizado. A parte protegida deve avisar, permitir controle da defesa e cooperar. Acordo não pode admitir culpa ou impor obrigação não monetária sem consentimento."] },
      { title: "31. Força maior", body: ["Nenhuma parte responde por atraso fora de controle razoável, inclusive eventos de energia, internet, cloud, trabalho, governo ou natureza, exceto pagamento por serviço já prestado. A parte afetada mitigará razoavelmente."] },
      { title: "32. Alterações", body: ["Podemos melhorar o serviço e atualizar estes Termos. Mudanças jurídicas materiais serão avisadas no produto, por e-mail ou site antes de vigorar quando razoável. Uso posterior vale como aceite onde permitido; alteração material pode exigir novo aceite eletrônico."] },
      { title: "33. Avisos", body: [`Avisos jurídicos à Ametrine Labs devem ir para ${REVORY_LEGAL.supportEmail}. Podemos avisar pelo e-mail da conta ou no REVORY. Suporte operacional não é aviso jurídico formal salvo identificação clara.`] },
      { title: "34. Cessão", body: ["Nenhuma parte pode ceder sem consentimento, exceto a afiliada ou em fusão, reorganização ou venda substancial de ativos, com assunção das obrigações. Cessão ilícita é nula."] },
      { title: "35. Independência e renúncia", body: ["Cláusula inexequível será limitada ao mínimo e o restante permanece. Não exigir uma obrigação não é renúncia; renúncia deve ser escrita e específica."] },
      { title: "36. Integralidade e prevalência", body: ["Estes Termos, Pedido, DPA, Aviso de Privacidade e Política de Reembolso formam o contrato. Pedido assinado prevalece nos pontos comerciais; DPA no tratamento de Dados Pessoais do Cliente; depois estes Termos. Texto padrão de pedido de compra não altera o contrato."] },
      { title: "37. Sobrevivência", body: ["Pagamento, confidencialidade, propriedade intelectual, dados, ressalvas, responsabilidade, indenização, disputas e disposições que por natureza sobrevivem continuam após a rescisão."] },
      { title: "38. Aceite eletrônico", body: ["Clicar para criar conta ou iniciar checkout, ou aceitar eletronicamente Pedido, equivale a assinatura onde permitido. O REVORY pode guardar usuário, workspace, versões, evento, contexto e data/hora como evidência."] },
      { title: "39. Lei, foro e contato", body: [`Aplica-se a lei brasileira. O foro de São Paulo, SP, é eleito, ressalvados foro obrigatório do consumidor, competência da autoridade de proteção de dados e demais direitos irrenunciáveis. Contato: ${REVORY_LEGAL.supportEmail}.`] },
    ],
  },
};

export const privacyDocuments: Record<LegalLocale, LegalDocument> = {
  en: {
    kicker: "Privacy Notice",
    title: "How REVORY handles personal data.",
    description: `${company} operates REVORY. This Notice explains our roles under Brazil’s LGPD and the practical boundaries of the product.`,
    sections: [
      { title: "1. Our roles", body: ["Ametrine Labs is controller for account, authentication, security, billing, support, service usage, operations and commercial relationship data. For personal data in contractor CSV/XLSX exports and related evidence, Ametrine Labs generally acts as processor/operator on the business customer’s documented instructions; that customer remains controller."] },
      { title: "2. Data, sources, purposes and legal bases", body: ["Account and authentication data come from you or Google and are used for access, identity, fraud prevention and contract performance. Workspace settings and usage events come from your use and support service delivery, security and legitimate operational interests. Billing identifiers come from Stripe for contract performance, accounting and legal duties. Support messages come from you to answer requests. Customer export data comes from files you submit to produce the requested analysis under the Customer’s instructions and lawful basis."] },
      { title: "3. Imported evidence", body: ["REVORY processes supported CSV/XLSX content, external IDs, mapping choices, provenance, values, dates, statuses and relationship fields. Original files are parsed in application memory; canonical records, mappings, findings and audit evidence are stored in the workspace database. Do not upload payment-card data, health data, credentials or data unrelated to the supported service."] },
      { title: "4. AI processing", body: ["For canonical mapping assistance, the AI provider receives column headers, inferred types, fill rates and redacted shape labels rather than raw rows. Other optional legacy or bounded features may receive limited context such as a first name, offer label, workspace label or deterministic metrics to generate a narrow classification, explanation or draft. AI is optional where presented, cannot approve imports or financial findings and is not used for solely automated decisions producing legal or similarly significant effects."] },
      { title: "5. Sharing", body: ["We disclose data only to the subprocessors listed in the Subprocessor Notice, people authorized by the Customer, professional advisers under confidentiality, authorities when legally required, and a successor in a lawful corporate transaction. REVORY does not sell personal data or use Customer Data for third-party advertising."] },
      { title: "6. International transfers", body: ["Some providers may process data outside Brazil. We apply contractual, technical and organizational safeguards and will use a transfer mechanism permitted by LGPD and ANPD Resolution CD/ANPD No. 19/2024 when required. The exact production mechanism and any required standard contractual clauses are subject to final legal confirmation and will be reflected in the DPA or applicable Order before reliance on that mechanism."] },
      { title: "7. Retention", body: ["Active workspace analysis defaults to 365 days and can be configured to 30, 90, 180 or 365 days; the scheduled retention process removes expired import sessions, findings, analysis runs, snapshots and evidence events. Self-service deletion removes supported analysis data immediately. Account, legal-acceptance, security, billing, tax, support and backup records are retained only while reasonably needed for their purpose or legal obligations; the final period by category remains an internal legal/operations decision and is not represented here as a fixed unimplemented deadline."] },
      { title: "8. Export, correction and deletion", body: ["Workspace users can export available stored workspace data and delete supported analysis data in Settings. Account closure, correction outside self-service tools or deletion requests may be sent to support. We verify identity and authority and may retain records when law, security, dispute preservation or backup cycles require it."] },
      { title: "9. Your LGPD rights", body: ["Subject to applicable conditions, a data subject may request confirmation, access, correction, anonymization, blocking or deletion of unnecessary or unlawfully processed data, portability, information about sharing, consent information and revocation, review of qualifying automated decisions, or opposition. End customers should normally contact the contractor that controls the imported record; we assist that Customer under the DPA."] },
      { title: "10. Security and incidents", body: ["We use the measures described in the Security Overview. No system is risk-free. If an incident affects Customer Personal Data, we notify the Customer without undue delay after becoming aware and provide available information needed for its legal assessment. We do not promise an unsupported fixed notification hour."] },
      { title: "11. Cookies and telemetry", body: ["REVORY uses essential authentication and security storage. Production may use Vercel Web Analytics and Speed Insights for aggregated usage and performance measurement; the configured analytics implementation is cookieless and does not include advertising trackers. See the Cookie Notice."] },
      { title: "12. Contact and ANPD", body: [`Send privacy requests to ${REVORY_LEGAL.privacyEmail}; do not email exports, passwords or card data. You may also petition Brazil’s Autoridade Nacional de Proteção de Dados (ANPD). No individual DPO is publicly named; this contact receives privacy requests for the company.`] },
      { title: "13. Changes", body: ["We will publish the effective date and version. Material changes will be communicated through the service, email or website when appropriate. Portuguese and English versions are intended to be materially equivalent; the Portuguese version governs for Brazilian mandatory-law interpretation if an unavoidable inconsistency exists."] },
    ],
  },
  "pt-BR": {
    kicker: "Aviso de Privacidade",
    title: "Como o REVORY trata dados pessoais.",
    description: `${company} opera o REVORY. Este Aviso explica nossos papéis na LGPD e os limites práticos do produto.`,
    sections: [
      { title: "1. Nossos papéis", body: ["A Ametrine Labs é controladora dos dados de conta, autenticação, segurança, cobrança, suporte, uso, operação e relação comercial. Nos dados pessoais dos arquivos CSV/XLSX e evidências relacionadas, atua em regra como operadora conforme instruções documentadas do cliente empresarial, que permanece controlador."] },
      { title: "2. Dados, fontes, finalidades e bases legais", body: ["Dados de conta e autenticação vêm de você ou do Google para acesso, identidade, prevenção a fraude e execução contratual. Configurações e eventos de uso vêm do uso do serviço para entrega, segurança e legítimos interesses operacionais. Identificadores de cobrança vêm do Stripe para contrato, contabilidade e obrigações legais. Mensagens de suporte vêm de você. Dados dos arquivos vêm do Cliente para a análise solicitada, conforme suas instruções e base legal."] },
      { title: "3. Evidências importadas", body: ["O REVORY trata conteúdo CSV/XLSX suportado, IDs externos, escolhas de mapeamento, proveniência, valores, datas, status e relações. Arquivos originais são lidos na memória da aplicação; registros canônicos, mapeamentos, achados e auditoria ficam no banco do workspace. Não envie dados de cartão, saúde, credenciais ou dados alheios ao serviço."] },
      { title: "4. Tratamento por IA", body: ["No mapeamento canônico, o provedor recebe cabeçalhos, tipos inferidos, taxas de preenchimento e rótulos de formato redigidos, não linhas brutas. Outros recursos opcionais legados ou limitados podem receber contexto restrito, como primeiro nome, rótulo de oferta/workspace ou métricas determinísticas, para classificação, explicação ou rascunho. IA não aprova importação ou achado financeiro nem toma decisão exclusivamente automatizada com efeito jurídico semelhante."] },
      { title: "5. Compartilhamento", body: ["Compartilhamos apenas com suboperadores publicados, pessoas autorizadas pelo Cliente, assessores sob confidencialidade, autoridades quando exigido e sucessor em operação societária lícita. O REVORY não vende dados pessoais nem usa Dados do Cliente para publicidade de terceiros."] },
      { title: "6. Transferência internacional", body: ["Alguns provedores podem tratar fora do Brasil. Aplicamos salvaguardas e usaremos mecanismo permitido pela LGPD e Resolução CD/ANPD nº 19/2024 quando exigido. O mecanismo exato de produção e eventuais cláusulas-padrão dependem de confirmação jurídica final e serão refletidos no DPA ou Pedido antes de sua utilização como fundamento."] },
      { title: "7. Retenção", body: ["A análise do workspace ativo tem padrão de 365 dias e opções 30, 90, 180 ou 365; o processo agendado remove sessões, achados, execuções, snapshots e eventos vencidos. A exclusão self-service remove dados de análise suportados imediatamente. Dados de conta, aceite, segurança, cobrança, tributos, suporte e backup ficam somente pelo necessário ou obrigatório; o prazo final por categoria permanece decisão interna jurídica/operacional, sem promessa pública de prazo ainda não implementado."] },
      { title: "8. Exportação, correção e exclusão", body: ["Usuários do workspace podem exportar dados disponíveis e excluir análise suportada em Configurações. Encerramento de conta, correção fora do self-service e exclusão podem ser solicitados ao suporte. Verificamos identidade e poderes e podemos reter por lei, segurança, litígio ou ciclo de backup."] },
      { title: "9. Direitos na LGPD", body: ["Conforme as condições legais, o titular pode pedir confirmação, acesso, correção, anonimização, bloqueio ou eliminação de dado desnecessário ou ilícito, portabilidade, informação sobre compartilhamento e consentimento, revogação, revisão de decisão automatizada aplicável ou oposição. Cliente final deve procurar primeiro a contratante controladora; auxiliamos o Cliente conforme o DPA."] },
      { title: "10. Segurança e incidentes", body: ["Aplicamos as medidas do Visão Geral de Segurança. Nenhum sistema é isento de risco. Em incidente com Dados Pessoais do Cliente, avisamos o Cliente sem demora indevida após ciência e fornecemos informação disponível para avaliação legal. Não prometemos prazo fixo em horas sem suporte operacional."] },
      { title: "11. Cookies e telemetria", body: ["O REVORY usa armazenamento essencial de autenticação e segurança. Em produção, pode usar Vercel Web Analytics e Speed Insights para uso agregado e desempenho; a configuração atual é sem cookies e não contém rastreadores de publicidade. Veja o Aviso de Cookies."] },
      { title: "12. Contato e ANPD", body: [`Envie pedidos a ${REVORY_LEGAL.privacyEmail}; não envie arquivos, senhas ou cartões por e-mail. Você também pode peticionar à Autoridade Nacional de Proteção de Dados (ANPD). Não há encarregado pessoa física divulgado; este contato recebe os pedidos da empresa.`] },
      { title: "13. Alterações", body: ["Publicaremos data e versão. Mudanças materiais serão comunicadas pelo serviço, e-mail ou site quando apropriado. Português e inglês buscam equivalência material; a versão em português prevalece na interpretação de lei brasileira obrigatória se houver inconsistência inevitável."] },
    ],
  },
};

export const refundDocuments: Record<LegalLocale, LegalDocument> = {
  en: {
    kicker: "Cancellation and Refund Policy",
    title: "Clear rules for each REVORY offer.",
    description: `This Policy applies to eligible purchases from ${company} and does not limit mandatory rights.`,
    sections: [
      { title: "1. Mandatory rights first", body: ["Nothing in this Policy excludes a non-waivable right under applicable law. If you qualify as a consumer in Brazil, the seven-day statutory right of withdrawal for an eligible distance purchase may apply under Article 49 of the Consumer Defense Code. Business classification does not eliminate a right that the law makes mandatory in the specific transaction."] },
      { title: "2. One-time Audit before commencement", body: ["A full refund may be requested before the one-time analysis begins. File attachment, profiling and mapping preview alone do not start the purchased run."] },
      { title: "3. When a one-time Audit begins", body: ["The service begins when you expressly confirm the reviewed mapping and use of the one-time Audit, and REVORY commits that import and creates the analysis read. The confirmation screen explains that the entitlement will be consumed."] },
      { title: "4. After commencement", body: ["After the run begins, the one-time fee is generally non-refundable because the contracted digital analysis has been delivered or started. Exceptions include duplicate, unauthorized or incorrect charges, a verified REVORY failure to provide the purchased service, and any refund required by law. Finding zero supported opportunities is not by itself service failure."] },
      { title: "5. Subscriptions", body: ["Monthly plans renew automatically until canceled. Cancellation takes effect at the end of the current paid period and stops later renewals. Current-period fees are not prorated solely because of early cancellation, except where law requires or a duplicate, unauthorized, incorrect charge or verified service failure applies. Access normally remains through the paid period."] },
      { title: "6. Requests", body: [`Use the secure Stripe billing portal to cancel a subscription or email ${REVORY_LEGAL.billingEmail} from the account owner address with workspace, purchase date and reason. Do not send card numbers or Customer Data. Approved refunds return to the original method; provider/bank settlement timing is outside our control.`] },
    ],
  },
  "pt-BR": {
    kicker: "Política de Cancelamento e Reembolso",
    title: "Regras claras para cada oferta REVORY.",
    description: `Esta Política se aplica a compras elegíveis de ${company} e não limita direitos obrigatórios.`,
    sections: [
      { title: "1. Direitos obrigatórios primeiro", body: ["Nada exclui direito irrenunciável aplicável. Se você se enquadrar como consumidor no Brasil, pode incidir o prazo legal de sete dias para arrependimento em compra à distância elegível, conforme o art. 49 do Código de Defesa do Consumidor. A classificação empresarial não elimina direito que a lei torne obrigatório na operação concreta."] },
      { title: "2. Auditoria avulsa antes do início", body: ["É possível pedir reembolso integral antes do início da análise avulsa. Anexar arquivo, gerar perfil e visualizar mapeamento não iniciam a execução comprada."] },
      { title: "3. Quando a Auditoria começa", body: ["O serviço começa quando você confirma expressamente o mapeamento revisado e o uso da Auditoria avulsa, e o REVORY efetiva a importação e cria a leitura. A tela informa que o direito será consumido."] },
      { title: "4. Depois do início", body: ["Depois do início, o valor avulso é em regra não reembolsável, pois a análise digital contratada começou ou foi entregue. Exceções incluem cobrança duplicada, não autorizada ou incorreta, falha verificada do REVORY em prestar o serviço e hipótese legal. Encontrar zero oportunidades suportadas não é, por si só, falha."] },
      { title: "5. Assinaturas", body: ["Planos mensais renovam automaticamente até o cancelamento. O cancelamento vigora ao fim do período pago e impede novas renovações. Não há proporcionalidade apenas por cancelamento antecipado, salvo lei, cobrança duplicada/não autorizada/incorreta ou falha verificada. O acesso normalmente segue até o fim do período."] },
      { title: "6. Solicitações", body: [`Cancele no portal seguro do Stripe ou envie e-mail de titular da conta para ${REVORY_LEGAL.billingEmail}, com workspace, data e motivo. Não envie número de cartão ou Dados do Cliente. Reembolso aprovado volta ao meio original; prazo bancário/do provedor não é controlado por nós.`] },
    ],
  },
};

export const securityDocuments: Record<LegalLocale, LegalDocument> = {
  en: {
    kicker: "Security Overview",
    title: "How REVORY protects evidence.",
    description: "A factual overview of controls implemented in the product. It is not a certification or guarantee of perfect security.",
    sections: [
      { title: "Workspace and access boundaries", body: ["Authenticated server-side context authorizes active workspace reads, writes, exports and finding changes. Password access uses email verification, durable throttling and session-version revocation; Google OAuth is available when configured."] },
      { title: "Imports and evidence integrity", body: ["CSV/XLSX upload policies limit file, row and batch volume, inspect file signatures and XLSX expansion, and reject workbook formulas. Canonical records preserve source IDs and provenance. Ambiguous or conflicting links remain visible and suppress unsupported financial output. Persistence uses transactions and idempotency boundaries."] },
      { title: "Infrastructure and secrets", body: ["Managed providers encrypt network traffic in transit and managed database storage at rest. Production secrets are held in managed environment variables. Stripe webhook signatures and a persistent replay ledger protect billing-event processing."] },
      { title: "Operations, backups and incidents", body: ["Scheduled retention, monitoring and operational checks are documented. Managed database backup/restore capabilities are used, and an isolated restore exercise has been recorded internally; this does not create a zero-loss or fixed-recovery guarantee. Incident response and escalation remain under Ametrine Labs operational control."] },
      { title: "Assurance boundary", body: ["REVORY does not claim SOC 2, ISO 27001, PCI DSS certification or any independent certification not actually obtained. Stripe handles hosted payment-card collection; REVORY does not store full card numbers. Independent application-security review remains a release gate for advanced paid scope."] },
      { title: "Report a vulnerability", body: [`Send suspected vulnerabilities privately to ${REVORY_LEGAL.securityEmail}. Do not send customer exports, passwords, recovery codes or exploit other users. See the Responsible Disclosure Policy for scope and safe-harbor conditions.`] },
    ],
  },
  "pt-BR": {
    kicker: "Visão Geral de Segurança",
    title: "Como o REVORY protege evidências.",
    description: "Resumo factual dos controles implementados. Não é certificação nem garantia de segurança perfeita.",
    sections: [
      { title: "Limites de workspace e acesso", body: ["O contexto autenticado no servidor autoriza leituras, gravações, exportações e alterações do workspace ativo. Senha usa verificação de e-mail, limitação durável e revogação por versão de sessão; OAuth Google fica disponível quando configurado."] },
      { title: "Importações e integridade", body: ["Políticas CSV/XLSX limitam volume, verificam assinatura e expansão do XLSX e rejeitam fórmulas. Registros guardam IDs e proveniência. Vínculos ambíguos/conflitantes seguem visíveis e suprimem valor financeiro sem suporte. Persistência usa transações e idempotência."] },
      { title: "Infraestrutura e segredos", body: ["Provedores gerenciados criptografam tráfego em trânsito e armazenamento de banco em repouso. Segredos de produção ficam em variáveis gerenciadas. Assinatura de webhook e ledger persistente protegem eventos Stripe."] },
      { title: "Operações, backups e incidentes", body: ["Retenção agendada, monitoramento e verificações são documentados. Usamos backup/restore do banco gerenciado e registramos exercício isolado; isso não garante perda zero ou prazo fixo. Resposta a incidente fica sob controle operacional da Ametrine Labs."] },
      { title: "Limite de certificações", body: ["O REVORY não alega SOC 2, ISO 27001, certificação PCI DSS ou outra independente não obtida. Stripe coleta cartão no checkout hospedado; REVORY não guarda número completo. Revisão independente de segurança segue como gate para escopo pago avançado."] },
      { title: "Relate vulnerabilidade", body: [`Envie de forma privada a ${REVORY_LEGAL.securityEmail}. Não envie arquivos, senhas ou códigos nem explore outros usuários. Veja a Política de Divulgação Responsável para escopo e safe harbor.`] },
    ],
  },
};

export const cookieDocuments: Record<LegalLocale, LegalDocument> = {
  en: { kicker: "Cookie Notice", title: "Essential storage, without advertising trackers.", description: "This notice describes the browser storage observed in the current REVORY implementation.", sections: [
    { title: "Essential authentication", body: ["REVORY authentication uses strictly necessary session, callback, CSRF and security cookies or equivalent browser storage. These enable sign-in, keep sessions secure and route you back to the requested page. Blocking them may prevent account access."] },
    { title: "Analytics and performance", body: ["Production may load Vercel Web Analytics and Speed Insights. The current Web Analytics implementation is cookieless and reports anonymized/aggregated usage; Speed Insights measures web-performance signals. REVORY does not configure advertising, cross-site profiling or marketing-pixel cookies."] },
    { title: "Consent boundary", body: ["Because the current implementation uses necessary storage and cookieless operational telemetry, REVORY does not show a cosmetic cookie banner. If a future feature introduces non-essential cookies, it must remain disabled until a consent control offers equally accessible accept, reject and preference choices where required."] },
    { title: "Contact", body: [`Questions can be sent to ${REVORY_LEGAL.privacyEmail}. Browser settings can delete or block storage, but essential-cookie blocking may break sign-in.`] },
  ] },
  "pt-BR": { kicker: "Aviso de Cookies", title: "Armazenamento essencial, sem rastreadores de publicidade.", description: "Este aviso descreve o armazenamento observado na implementação atual do REVORY.", sections: [
    { title: "Autenticação essencial", body: ["A autenticação usa cookies estritamente necessários de sessão, callback, CSRF e segurança, ou armazenamento equivalente. Eles permitem login, protegem a sessão e retornam à página pedida. Bloqueá-los pode impedir acesso."] },
    { title: "Analytics e desempenho", body: ["Produção pode carregar Vercel Web Analytics e Speed Insights. Web Analytics atual opera sem cookies e reporta uso anonimizado/agregado; Speed Insights mede desempenho web. Não configuramos cookies de publicidade, perfil entre sites ou pixels de marketing."] },
    { title: "Limite de consentimento", body: ["Como há apenas armazenamento necessário e telemetria operacional sem cookies, o REVORY não mostra banner cosmético. Se recurso futuro introduzir cookies não essenciais, ele deve ficar desativado até existir controle com aceitar, rejeitar e preferências igualmente acessíveis quando exigido."] },
    { title: "Contato", body: [`Dúvidas: ${REVORY_LEGAL.privacyEmail}. O navegador pode apagar ou bloquear armazenamento, mas bloquear o essencial pode quebrar o login.`] },
  ] },
};

export const disclosureDocuments: Record<LegalLocale, LegalDocument> = {
  en: { kicker: "Responsible Disclosure", title: "Report security issues safely.", description: "We welcome good-faith reports that help protect REVORY customers.", sections: [
    { title: "How to report", body: [`Email ${REVORY_LEGAL.securityEmail} with a concise description, affected URL or component, reproduction steps and impact. Use test data and remove secrets. We will acknowledge and triage in a commercially reasonable manner but do not promise a fixed response or bounty.`] },
    { title: "In scope", body: ["REVORY-owned application and API authorization, workspace isolation, authentication, import handling, exports, billing-event handling and accidental disclosure of REVORY-managed data."] },
    { title: "Out of scope", body: ["Social engineering, phishing, denial of service, credential stuffing, spam, physical attacks, testing third-party infrastructure outside REVORY’s control, automated high-volume scanning, and issues requiring access to another person’s data."] },
    { title: "Safe harbor", body: ["If you act in good faith, avoid privacy harm and disruption, test only accounts/data you control, stop when sensitive data appears, do not extort or publicly disclose before remediation, and follow this policy, we will not pursue action merely for that compliant research. This does not authorize violation of law or third-party rights."] },
  ] },
  "pt-BR": { kicker: "Divulgação Responsável", title: "Relate falhas com segurança.", description: "Recebemos relatos de boa-fé que ajudem a proteger clientes REVORY.", sections: [
    { title: "Como relatar", body: [`Envie a ${REVORY_LEGAL.securityEmail} descrição, URL/componente, reprodução e impacto. Use dados de teste e remova segredos. Responderemos de forma comercialmente razoável, sem prometer prazo fixo ou recompensa.`] },
    { title: "No escopo", body: ["Autorização do app/API, isolamento de workspace, autenticação, importação, exportação, eventos de cobrança e exposição acidental de dados sob gestão do REVORY."] },
    { title: "Fora do escopo", body: ["Engenharia social, phishing, negação de serviço, credential stuffing, spam, ataque físico, teste de infraestrutura de terceiro, varredura automatizada de alto volume e problema que exija acessar dados de outra pessoa."] },
    { title: "Safe harbor", body: ["Se agir de boa-fé, evitar dano e interrupção, testar só contas/dados próprios, parar ao ver dado sensível, não extorquir nem divulgar antes da correção e seguir esta política, não buscaremos medida apenas por essa pesquisa compatível. Isso não autoriza violar lei ou direito de terceiro."] },
  ] },
};
