import "server-only";

import { prisma } from "@/db/prisma";

export async function buildWorkspaceExport(workspaceId: string) {
  const [
    workspace,
    imports,
    records,
    mappings,
    quoteRecoveryFindings,
    revenueRealizationFindings,
    quoteRecoveryRuns,
    intelligenceSnapshots,
    entitlements,
    settings,
    digest,
    auditEvents,
    evidenceEvents,
    legalAcceptances,
    legacyClients,
    legacyAppointments,
    legacyDataSources,
    legacyRevenueLeaks,
    aiImportBatches,
    aiRevenueRecords,
    aiUsageRecords,
    aiProviderBuckets,
    aiMappings,
    aiSnapshots,
    aiSnapshotInputs,
    aiFindings,
    aiScanOrders,
    aiScanGrants,
    aiReviewEvents,
  ] = await Promise.all([
    prisma.workspace.findUnique({ where: { id: workspaceId }, select: { id: true, name: true, slug: true, status: true, createdAt: true, updatedAt: true } }),
    prisma.canonicalImportSession.findMany({ where: { workspaceId } }),
    prisma.canonicalRecord.findMany({ where: { workspaceId } }),
    prisma.savedCanonicalMapping.findMany({ where: { workspaceId } }),
    prisma.quoteRecoveryFinding.findMany({ where: { workspaceId } }),
    prisma.revenueRealizationFinding.findMany({ where: { workspaceId } }),
    prisma.quoteRecoveryAnalysisRun.findMany({ where: { workspaceId } }),
    prisma.revenueIntelligenceSnapshot.findMany({ where: { workspaceId } }),
    prisma.workspaceEntitlement.findMany({ where: { workspaceId }, select: { offerKey: true, status: true, startsAt: true, endsAt: true } }),
    prisma.workspaceDataSettings.findUnique({ where: { workspaceId } }),
    prisma.quoteRecoveryDigestPreference.findUnique({ where: { workspaceId } }),
    prisma.workspaceAuditEvent.findMany({ where: { workspaceId }, orderBy: { createdAt: "asc" } }),
    prisma.revoryEvidenceEvent.findMany({ where: { workspaceId }, orderBy: { observedAt: "asc" } }),
    prisma.legalAcceptance.findMany({ where: { workspaceId }, orderBy: { acceptedAt: "asc" }, select: { acceptedAt: true, contextJson: true, documentVersionsJson: true, event: true, id: true, locale: true, userId: true, workspaceId: true } }),
    prisma.client.findMany({ where: { workspaceId } }),
    prisma.appointment.findMany({ where: { workspaceId } }),
    prisma.dataSource.findMany({ where: { workspaceId } }),
    prisma.revenueLeak.findMany({ where: { workspaceId } }),
    prisma.aiIntegrityImportBatch.findMany({ where: { workspaceId } }),
    prisma.aiIntegrityRevenueRecord.findMany({ where: { workspaceId } }),
    prisma.aiIntegrityUsageRecord.findMany({ where: { workspaceId } }),
    prisma.aiIntegrityProviderBucket.findMany({ where: { workspaceId } }),
    prisma.aiIntegrityMapping.findMany({ where: { workspaceId } }),
    prisma.aiIntegritySnapshot.findMany({ where: { workspaceId } }),
    prisma.aiIntegritySnapshotInput.findMany({ where: { workspaceId } }),
    prisma.aiIntegrityFinding.findMany({ where: { workspaceId } }),
    prisma.aiIntegrityScanOrder.findMany({ where: { workspaceId }, select: { id: true, workspaceId: true, offerVersion: true, amountMinor: true,
      currency: true, status: true, checkoutDriver: true, createdAt: true, paidAt: true } }),
    prisma.aiIntegrityScanGrant.findMany({ where: { workspaceId } }),
    prisma.aiIntegrityReviewEvent.findMany({ where: { workspaceId }, orderBy: { createdAt: "asc" } }),
  ]);
  if (!workspace) throw new Error("Workspace not found.");
  return {
    aiIntegrity: { importBatches: aiImportBatches, revenueRecords: aiRevenueRecords, usageRecords: aiUsageRecords, providerBuckets: aiProviderBuckets, mappings: aiMappings, snapshots: aiSnapshots, snapshotInputs: aiSnapshotInputs, findings: aiFindings, scanOrders: aiScanOrders, scanGrants: aiScanGrants, reviewEvents: aiReviewEvents },
    auditEvents,
    evidenceEvents,
    digest,
    entitlements,
    exportedAt: new Date().toISOString(),
    imports,
    intelligenceSnapshots,
    legalAcceptances,
    mappings,
    legacyMigrationData: { appointments: legacyAppointments, clients: legacyClients, dataSources: legacyDataSources, revenueLeaks: legacyRevenueLeaks },
    quoteRecoveryFindings,
    quoteRecoveryRuns,
    records,
    revenueRealizationFindings,
    schemaVersion: 7,
    settings,
    workspace,
  };
}
