import type {
  RevoryAppointmentCsvColumn,
  RevoryClientCsvColumn,
  RevoryCsvColumnAliases,
} from "@/types/imports";

export const revoryAppointmentsCsvHeaderSynonyms = {
  appointment_external_id: [
    "appointment id",
    "appointmentid",
    "appt id",
    "booking id",
    "bookingid",
    "visit id",
  ],
  booked_at: [
    "booked date",
    "booking date",
    "created at",
    "created_on",
    "date booked",
  ],
  canceled_at: [
    "cancelled at",
    "cancelled date",
    "canceled date",
    "cancel date",
  ],
  client_email: [
    "email",
    "client email",
    "patient email",
    "customer email",
    "email address",
  ],
  client_external_id: [
    "client id",
    "patient id",
    "customer id",
    "contact id",
    "patient external id",
  ],
  client_full_name: [
    "full name",
    "client name",
    "patient name",
    "customer name",
    "name",
  ],
  client_phone: [
    "phone",
    "phone number",
    "mobile",
    "mobile phone",
    "client phone",
    "patient phone",
  ],
  estimated_revenue: [
    "revenue",
    "amount",
    "value",
    "price",
    "service value",
    "estimated value",
  ],
  location_name: ["location", "clinic", "unit", "branch", "location name"],
  provider_name: [
    "provider",
    "staff",
    "specialist",
    "therapist",
    "doctor",
    "provider name",
  ],
  scheduled_at: [
    "appointment date",
    "appointment datetime",
    "appointment time",
    "date time",
    "scheduled date",
    "scheduled for",
    "scheduled time",
    "start",
    "start time",
    "visit date",
  ],
  service_name: [
    "service",
    "treatment",
    "procedure",
    "appointment type",
    "service type",
  ],
  source_notes: ["notes", "remarks", "internal notes", "comments", "comment"],
  status: [
    "appointment status",
    "appt status",
    "booking status",
    "state",
    "appointment_state",
  ],
} satisfies RevoryCsvColumnAliases<RevoryAppointmentCsvColumn>;

export const revoryClientsCsvHeaderSynonyms = {
  email: ["client email", "patient email", "customer email", "email address"],
  external_id: [
    "client id",
    "patient id",
    "customer id",
    "contact id",
    "patient external id",
  ],
  full_name: ["name", "client name", "patient name", "customer name", "full name"],
  last_visit_at: ["last visit", "last visit date", "latest visit", "last seen at"],
  notes: ["comment", "comments", "remarks", "internal notes"],
  phone: ["mobile", "phone number", "mobile phone", "client phone", "patient phone"],
  tags: ["labels", "segments", "categories"],
  total_visits: ["visits", "visit count", "number of visits", "visit total"],
} satisfies RevoryCsvColumnAliases<RevoryClientCsvColumn>;
