import { notFound } from "next/navigation";
import { AiMarketingNav, AiMarketingFooter } from "@/components/ai-integrity/AiMarketing";
import { isAiIntegrityExperienceEnabled } from "@/services/ai-integrity/experience";

export const metadata = { title: "REVORY · Synthetic test preview conditions", robots: { index: false, follow: false } };

export default function AiIntegrityPreviewPolicy() {
  if (!isAiIntegrityExperienceEnabled()) notFound();
  return <main className="ai-integrity-experience min-h-screen [font-family:var(--font-dm-sans)]"><AiMarketingNav /><article className="mx-auto max-w-3xl space-y-8 px-5 py-14 md:px-8"><header><p className="rev-kicker">Synthetic test preview · test-v1</p><h1 className="mt-5 [font-family:var(--font-instrument-serif)] text-5xl font-normal">A defined scope for this test.</h1><p className="mt-5 text-sm leading-8 text-[color:var(--text-muted)]">This preview is for synthetic records and test purchases. It is not available for customer analysis or commercial use.</p></header>
    <section id="offer" className="rev-shell-panel rounded-2xl p-6"><h2 className="text-lg font-bold">One report, one closed period</h2><p className="mt-3 text-sm leading-8 text-[color:var(--text-muted)]">The USD 99 amount is a one-time pricing hypothesis shown in a test checkout. It creates no subscription. A confirmed test payment provides one immutable report from three reviewed source exports. Failed execution preserves the scan; requesting the same saved report does not use an additional purchase.</p><p className="mt-3 text-sm leading-8 text-[color:var(--text-muted)]">The report covers observed provider spend without reliable customer attribution and comparable ledger/provider usage differences. Revenue is context. It does not calculate revenue leakage, margin or credit balances.</p></section>
    <section id="payment" className="rev-shell-panel rounded-2xl p-6"><h2 className="text-lg font-bold">Test payments and cancellation</h2><p className="mt-3 text-sm leading-8 text-[color:var(--text-muted)]">Local simulation and Stripe test mode move no real funds. Each checkout identifies its environment. Leaving checkout does not activate a scan. Only verified payment confirmation can activate it. A test refund revokes unused scan access. Commercial pricing, refund terms and customer availability require review before any real purchase.</p></section>
    <section id="privacy" className="rev-shell-panel rounded-2xl p-6"><h2 className="text-lg font-bold">Synthetic evidence only</h2><p className="mt-3 text-sm leading-8 text-[color:var(--text-muted)]">Use the provided sample files or other synthetic fixtures. Do not upload customer, financial, personal or confidential records. Reviewed files become workspace evidence and may be included in immutable reports and data exports. Reports follow workspace retention; download JSON to preserve replayable inputs. CSV summarizes findings.</p></section>
    <section id="security" className="rev-shell-panel rounded-2xl p-6"><h2 className="text-lg font-bold">Read-only and workspace scoped</h2><p className="mt-3 text-sm leading-8 text-[color:var(--text-muted)]">This preview reads uploaded exports. It does not connect to or write into customer systems. Imported IDs and confirmed mappings determine attribution; ambiguous records remain visible. Authenticated workspace access protects saved evidence. This preview does not establish production security certification or authorize a customer beta.</p></section>
  </article><AiMarketingFooter /></main>;
}
