import assert from "node:assert/strict";
import { prisma } from "../db/prisma";
import { consentAiSourceRehearsal, syncAiSourceRehearsal, revokeAiSourceRehearsal, getAiSourceArtifact, listAiSourceRehearsals } from "../services/ai-integrity/connected-sources";
import { buildWorkspaceExport } from "../services/data-portability/workspace-export";
import { enforceWorkspaceRetention } from "../services/data-portability/enforce-retention";
import { aiSourceFixtureTransport } from "../services/ai-integrity/source-fixtures";

if (!/^\/revory_sprint1_[a-f0-9]{12}$/.test(new URL(process.env.DATABASE_URL!).pathname)) throw new Error("Use disposable DB harness.");
process.env.REVORY_AI_SAAS_PREVIEW = "true"; process.env.REVORY_AI_SOURCE_REHEARSAL = "true";
try {
  const user = await prisma.user.create({ data: { email: "sprint7@example.invalid" } });
  const ws = await prisma.workspace.create({ data: { name: "Synthetic source rehearsal", slug: "sprint7", ownerUserId: user.id } });
  const other = await prisma.workspace.create({ data: { name: "Other source rehearsal", slug: "sprint7-other", ownerUserId: user.id } });
  await assert.rejects(() => consentAiSourceRehearsal(ws.id, user.id, { provider: "OPENAI", syntheticConsentConfirmed: true, apiKey: "not_a_key" }), /Unsupported/);
  await assert.rejects(() => consentAiSourceRehearsal(ws.id, user.id, { provider: "OPENAI", syntheticConsentConfirmed: false }), /Confirm/);
  const [first, repeated] = await Promise.all([consentAiSourceRehearsal(ws.id, user.id, { provider: "OPENAI", syntheticConsentConfirmed: true }), consentAiSourceRehearsal(ws.id, user.id, { provider: "OPENAI", syntheticConsentConfirmed: true })]);
  assert.equal(first.id, repeated.id); assert.equal(await prisma.aiIntegritySourceConnection.count(), 1);
  const request = { connectionId: first.id, requestKey: "read_concurrent_001", windowStart: "2026-08-01T00:00:00.000Z", windowEnd: "2026-08-02T00:00:00.000Z", lagHours: 24 };
  await assert.rejects(() => syncAiSourceRehearsal(other.id, user.id, request), /consent/);
  const [read, replay] = await Promise.all([syncAiSourceRehearsal(ws.id, user.id, request), syncAiSourceRehearsal(ws.id, user.id, request)]);
  assert.equal(read.sync.id, replay.sync.id); assert.notEqual(read.replayed, replay.replayed); assert.equal(await prisma.aiIntegritySourceSync.count(), 1);
  const evidence = await getAiSourceArtifact(ws.id, read.sync.id); assert.ok(evidence); assert.equal(await getAiSourceArtifact(other.id, read.sync.id), null);
  await assert.rejects(() => syncAiSourceRehearsal(ws.id, user.id, { ...request, windowEnd: "2026-08-03T00:00:00.000Z" }), /reused/);
  const skipped = await syncAiSourceRehearsal(ws.id, user.id, { ...request, requestKey: "read_already_done_002" }); assert.equal(skipped.sync.status, "SKIPPED"); assert.equal(skipped.sync.artifactJson, null);
  const incremental = await syncAiSourceRehearsal(ws.id, user.id, { ...request, requestKey: "read_incremental_003", windowEnd: "2026-08-03T00:00:00.000Z" }); assert.equal(incremental.sync.effectiveStart?.toISOString(), request.windowEnd);
  const checkpoint = await prisma.aiIntegritySourceConnection.findUniqueOrThrow({ where: { id: first.id } }); assert.equal(checkpoint.completeThrough?.toISOString(), "2026-08-03T00:00:00.000Z");
  await assert.rejects(() => syncAiSourceRehearsal(ws.id, user.id, { ...request, requestKey: "read_gap_rejected_004", windowStart: "2026-08-04T00:00:00.000Z", windowEnd: "2026-08-05T00:00:00.000Z" }), /gap/);
  assert.equal(await prisma.aiIntegritySourceSync.count(), 3);
  await assert.rejects(() => syncAiSourceRehearsal(ws.id, user.id, { ...request, requestKey: "read_provider_failure_007", windowEnd: "2026-08-04T00:00:00.000Z" }, async (read) => { if (read.query.page) throw new Error("Synthetic rate-limit failure"); return aiSourceFixtureTransport(read); }), /rate-limit/);
  assert.equal(await prisma.aiIntegritySourceSync.count(), 3); assert.equal((await prisma.aiIntegritySourceConnection.findUniqueOrThrow({ where: { id: first.id } })).completeThrough?.toISOString(), "2026-08-03T00:00:00.000Z", "Failed pagination must not advance the checkpoint");
  assert.deepEqual(await getAiSourceArtifact(ws.id, read.sync.id), evidence, "Incremental reads never rewrite earlier evidence");
  await assert.rejects(() => revokeAiSourceRehearsal(other.id, user.id, { connectionId: first.id }), /unavailable/);
  await revokeAiSourceRehearsal(ws.id, user.id, { connectionId: first.id });
  await assert.rejects(() => syncAiSourceRehearsal(ws.id, user.id, request), /revoked/);
  const reconsented = await consentAiSourceRehearsal(ws.id, user.id, { provider: "OPENAI", syntheticConsentConfirmed: true }); assert.equal(reconsented.generation, 2); assert.equal(reconsented.completeThrough, null);
  await assert.rejects(() => syncAiSourceRehearsal(ws.id, user.id, request), /reused/);
  const stripe = await consentAiSourceRehearsal(ws.id, user.id, { provider: "STRIPE", syntheticConsentConfirmed: true });
  await syncAiSourceRehearsal(ws.id, user.id, { ...request, connectionId: stripe.id, requestKey: "read_stripe_context_005" });
  assert.equal(await prisma.aiIntegrityImportBatch.count(), 0, "Staged source reads do not import or run scans"); assert.equal(await prisma.aiIntegrityScanGrant.count(), 0);
  assert.equal((await listAiSourceRehearsals(ws.id)).length, 2);
  assert.ok(JSON.stringify(await buildWorkspaceExport(ws.id)).includes(read.sync.id));
  await assert.rejects(() => prisma.aiIntegritySourceSync.create({ data: { ...read.sync, id: "cross_tenant_source", workspaceId: other.id, requestKey: "read_illegal_reference_006", artifactJson: read.sync.artifactJson! } }));
  await prisma.aiIntegritySourceSync.update({ where: { id: read.sync.id }, data: { createdAt: new Date("2024-01-01T00:00:00Z") } });
  await enforceWorkspaceRetention(ws.id, new Date("2026-10-01T00:00:00Z")); assert.equal(await getAiSourceArtifact(ws.id, read.sync.id), null);
  await prisma.aiIntegritySourceSync.update({ where: { id: incremental.sync.id }, data: { artifactHash: "0".repeat(64) } }); await assert.rejects(() => getAiSourceArtifact(ws.id, incremental.sync.id), /integrity/);
  process.env.REVORY_AI_SOURCE_REHEARSAL = "false"; assert.deepEqual(await listAiSourceRehearsals(ws.id), []); await assert.rejects(() => syncAiSourceRehearsal(ws.id, user.id, request), /unavailable/);
  await prisma.workspace.delete({ where: { id: ws.id } }); assert.equal(await prisma.aiIntegritySourceSync.count(), 0);
  console.log("Sprint 7 DB PASS: consent/idempotency, ordered incremental checkpoints, skipped windows/gap rejection, revocation/reconsent, workspace FKs, artifact tamper detection, export/retention, no automatic import/scan/purchase and feature gate.");
} finally { await prisma.$disconnect(); }
