import assert from "node:assert/strict";
import { Prisma } from "@prisma/client";
import { prisma } from "../db/prisma";
import { sprint8Fixture } from "./fixtures/ai-saas/sprint-8";
import { seedSprint8Report } from "./fixtures/ai-saas/sprint-8-db";
import { compareAiMonitorReports, getAiMonitorArtifact, acknowledgeAiMonitorAlert } from "../services/ai-integrity/monitoring";
import { exportAiIntegrityScan, getAiIntegrityScan } from "../services/ai-integrity/scan";
import { buildWorkspaceExport } from "../services/data-portability/workspace-export";
import { enforceWorkspaceRetention } from "../services/data-portability/enforce-retention";

const database = new URL(process.env.DATABASE_URL!);
if (!/^\/revory_sprint1_[a-f0-9]{12}$/.test(database.pathname) || !["localhost", "127.0.0.1", "::1"].includes(database.hostname)) throw new Error("Use disposable DB harness.");
try {
  const user = await prisma.user.create({ data: { email: "sprint8@example.invalid" } });
  const workspace = await prisma.workspace.create({ data: { name: "Synthetic monitor", slug: "sprint8", ownerUserId: user.id } });
  const other = await prisma.workspace.create({ data: { name: "Other workspace", slug: "sprint8-other", ownerUserId: user.id } });
  const a = await seedSprint8Report(workspace.id, user.id, sprint8Fixture(1));
  const b = await seedSprint8Report(workspace.id, user.id, sprint8Fixture(2, "140", "2.5"));
  const c = await seedSprint8Report(workspace.id, user.id, sprint8Fixture(3, "100", "0"));
  const original = exportAiIntegrityScan((await getAiIntegrityScan(workspace.id, a.snapshotId))!, "json");
  process.env.REVORY_AI_SAAS_PREVIEW = "true"; process.env.REVORY_AI_MONITOR_REHEARSAL = "false";
  const input = { baselineSnapshotId: a.snapshotId, currentSnapshotId: b.snapshotId, requestKey: "concurrent_monitor_001", syntheticDataConfirmed: true };
  await assert.rejects(() => compareAiMonitorReports(workspace.id, user.id, input), /unavailable/);
  process.env.REVORY_AI_MONITOR_REHEARSAL = "true";
  await assert.rejects(() => compareAiMonitorReports(workspace.id, user.id, { ...input, syntheticDataConfirmed: false }), /Confirm/);
  await assert.rejects(() => compareAiMonitorReports(workspace.id, user.id, { ...input, apiKey: "invalid" }), /fields/);
  await assert.rejects(() => compareAiMonitorReports(other.id, user.id, input), /workspace/);
  const [first, replay] = await Promise.all([compareAiMonitorReports(workspace.id, user.id, input), compareAiMonitorReports(workspace.id, user.id, input)]);
  assert.equal(first.comparison.id, replay.comparison.id); assert.equal(first.replayed !== replay.replayed, true);
  assert.equal(await prisma.aiIntegrityMonitorComparison.count(), 1); assert.equal(await prisma.aiIntegrityMonitorAlert.count(), 2);
  assert.equal((await compareAiMonitorReports(workspace.id, user.id, { ...input, requestKey: "same_pair_dedup_002" })).comparison.id, first.comparison.id);
  await assert.rejects(() => compareAiMonitorReports(workspace.id, user.id, { ...input, currentSnapshotId: c.snapshotId }), /reused/);
  const saved = await getAiMonitorArtifact(workspace.id, first.comparison.id); assert.equal(saved?.artifact.counts.persistent, 2);
  assert.equal(await getAiMonitorArtifact(other.id, first.comparison.id), null);
  const alert = await prisma.aiIntegrityMonitorAlert.findFirstOrThrow({ where: { workspaceId: workspace.id } });
  await assert.rejects(() => acknowledgeAiMonitorAlert(other.id, user.id, { alertId: alert.id }), /workspace/);
  const acknowledged = await Promise.all([acknowledgeAiMonitorAlert(workspace.id, user.id, { alertId: alert.id }), acknowledgeAiMonitorAlert(workspace.id, user.id, { alertId: alert.id })]);
  assert.equal(acknowledged[0].acknowledgedAt?.toISOString(), acknowledged[1].acknowledgedAt?.toISOString());
  assert.equal(await prisma.workspaceAuditEvent.count({ where: { action: "AI_MONITOR_REHEARSAL_ALERT_ACKNOWLEDGED" } }), 1);
  assert.equal((await getAiMonitorArtifact(workspace.id, first.comparison.id))?.comparison.artifactHash, saved?.comparison.artifactHash);
  assert.equal(exportAiIntegrityScan((await getAiIntegrityScan(workspace.id, a.snapshotId))!, "json"), original);
  const resolved = await compareAiMonitorReports(workspace.id, user.id, { ...input, baselineSnapshotId: b.snapshotId, currentSnapshotId: c.snapshotId, requestKey: "resolved_monitor_003" });
  assert.equal((await getAiMonitorArtifact(workspace.id, resolved.comparison.id))?.artifact.counts.noLongerObserved, 2);
  assert.equal(await prisma.aiIntegrityMonitorAlert.count({ where: { comparisonId: resolved.comparison.id } }), 0);
  const exported = await buildWorkspaceExport(workspace.id); assert.equal(exported.schemaVersion, 9); assert.equal(exported.monitoringRehearsal.comparisons.length, 2);
  assert.equal(await prisma.aiIntegrityScanOrder.count(), 0); assert.equal(await prisma.aiIntegrityScanGrant.count(), 0); assert.equal(await prisma.aiIntegritySourceConnection.count(), 0);
  await assert.rejects(() => prisma.aiIntegrityMonitorComparison.create({ data: { ...first.comparison, artifactJson: first.comparison.artifactJson as Prisma.InputJsonValue, id: "cross_tenant_monitor", workspaceId: other.id, requestKey: "cross_tenant_monitor_004" } }));
  await prisma.aiIntegrityMonitorComparison.update({ where: { id: first.comparison.id }, data: { artifactHash: "0".repeat(64) } });
  await assert.rejects(() => getAiMonitorArtifact(workspace.id, first.comparison.id), /integrity/);
  await assert.rejects(() => compareAiMonitorReports(workspace.id, user.id, input), /integrity/);
  await prisma.aiIntegrityMonitorComparison.update({ where: { id: first.comparison.id }, data: { artifactHash: first.comparison.artifactHash } });
  await prisma.aiIntegritySnapshot.update({ where: { id: a.snapshotId }, data: { createdAt: new Date("2024-01-01T00:00:00Z") } });
  const retention = await enforceWorkspaceRetention(workspace.id, new Date("2026-10-01T00:00:00Z"));
  assert.equal(retention.deletedAiMonitorComparisons, 1); assert.equal(await prisma.aiIntegrityMonitorAlert.count(), 0);
  assert.equal(await getAiMonitorArtifact(workspace.id, first.comparison.id), null);
  // Existing snapshot-input RESTRICT contracts require evidence snapshots to retire before workspace/import deletion.
  await prisma.aiIntegritySnapshot.deleteMany({ where: { workspaceId: workspace.id } });
  assert.equal(await prisma.aiIntegrityMonitorComparison.count(), 0);
  await prisma.workspace.delete({ where: { id: workspace.id } });
  console.log("Sprint 8 DB PASS: synthetic/strict fields, isolation/FKs, concurrent replay and pair dedupe, bounded local alerts, acknowledgment audit, immutable scans/artifact, export v9 and retention/cascade. No subscription/provider connection created.");
} finally { await prisma.$disconnect(); }
